version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: landlord_dashboard
      POSTGRES_USER: landlord_user
      POSTGRES_PASSWORD: landlord_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U landlord_user -d landlord_dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - landlord-network

  backend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgresql://landlord_user:landlord_pass@postgres:5432/landlord_dashboard
      PORT: 3002
      NODE_ENV: development
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules
    networks:
      - landlord-network

  frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3002
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules
    networks:
      - landlord-network

networks:
  landlord-network:
    driver: bridge

volumes:
  postgres_data:
  backend_modules:
  frontend_modules: